---
# K8S Service for expose pod 

# apiVersion: v1
# kind: Service
# metadata:
#   name: basic-flask-api
# spec:
#   type: LoadBalancer
#   selector:
#     app: basic-flask-api
#   ports:
#   - port: 80
#     targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-flask-api
  labels:
    app: basic-flask-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-flask-api
  template:
    metadata:
      labels:
        app: basic-flask-api
    spec:
      containers:
      - name: basic-flask-api
        image: oliveroscarlos/basic-flask-api:{{SHA}}
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
      - name: redis
        image: redis
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1