name: Build and Publish to Docker Hub
on:
  push:
    branches:
    - 'master'
    
jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: show tag
        run: echo "${{github.repository}}:${{ github.sha }}"
      - name: build image
        run: docker build ./ -t oliveroscarlos/basic-flask-api:${{ github.sha }}
      - name: push image to docker hub
        run: |
          docker login -u oliveroscarlos -p ${{ secrets.DOCKER_HUB_TOKEN}}
          docker push oliveroscarlos/basic-flask-api:${{ github.sha }}

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true

      - name: Authenticate gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: deploy to gke
        env:
          GOOGLE_PROJECT: ${{ secrets.PROJECT_ID }}
        run: |
          gcloud container clusters get-credentials gke-cluster-1 --region us-central1
          sed -i "s/GOOGLE_PROJECT/$PROJECT_ID/g" ks8-deployment-flask.yaml
          sed -i "s/{{SHA}}/${{ github.sha }}/g" ks8-deployment-flask.yaml
          kubectl apply -f ks8-deployment-flask.yaml
          kubectl rollout restart deployment/basic-flask-api